from pathlib import Path
# This project generates synthetic input data inside analysis.py so the repository stays small and reproducible.
Path(__file__).parent.joinpath("outputs").mkdir(exist_ok=True)
print("Synthetic data is generated by analysis.py with a fixed random seed.")
